<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="http://maven.apache.org/POM/4.0.0"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <artifactId>Lecture02</artifactId>
  <build>
    <plugins>
      <plugin>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <groupId>org.springframework.boot</groupId>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <executions>
          <execution>
            <configuration>
              <annotationProcessorPaths>
                <path>
                  <artifactId>lombok</artifactId>
                  <groupId>org.projectlombok</groupId>
                </path>
              </annotationProcessorPaths>
              <release>21</release>
            </configuration>
            <goals>
              <goal>compile</goal>
            </goals>
            <id>default-compile</id>
            <phase>compile</phase>
          </execution>
          <execution>
            <configuration>
              <release>21</release>
            </configuration>
            <goals>
              <goal>testCompile</goal>
            </goals>
            <id>default-testCompile</id>
            <phase>test-compile</phase>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
      </plugin>
      <plugin>
        <artifactId>maven-checkstyle-plugin</artifactId>
        <configuration>
          <configLocation>google_checks.xml</configLocation>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <id>default-cli</id>
            <phase>validate</phase>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
        <version>3.6.0</version>
      </plugin>
      <plugin>
        <artifactId>maven-pmd-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <id>default-cli</id>
            <phase>validate</phase>
          </execution>
        </executions>
        <groupId>org.apache.maven.plugins</groupId>
      </plugin>
      <plugin>
        <artifactId>spotbugs-maven-plugin</artifactId>
        <configuration>
          <effort>Max</effort>
          <omitVisitors>FindReturnRef</omitVisitors>
          <plugins>
            <plugin>
              <artifactId>findsecbugs-plugin</artifactId>
              <groupId>com.h3xstream.findsecbugs</groupId>
              <version>LATEST</version>
            </plugin>
          </plugins>
          <threshold>Normal</threshold>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <id>default-cli</id>
            <phase>verify</phase>
          </execution>
        </executions>
        <groupId>com.github.spotbugs</groupId>
      </plugin>
      <plugin>
        <artifactId>dependency-check-maven</artifactId>
        <configuration>
          <failBuildOnCVSS>10</failBuildOnCVSS>
          <nvdApiDelay>6500</nvdApiDelay>
          <nvdApiKeyEnvironmentVariable>NVD_API_KEY</nvdApiKeyEnvironmentVariable>
          <nvdApiResultsPerPage>200</nvdApiResultsPerPage>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>check</goal>
            </goals>
            <id>default-cli</id>
            <phase>verify</phase>
          </execution>
        </executions>
        <groupId>org.owasp</groupId>
        <version>12.2.2</version>
      </plugin>
      <plugin>
        <artifactId>jacoco-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
            <id>prepare</id>
          </execution>
          <execution>
            <goals>
              <goal>report</goal>
            </goals>
            <id>report</id>
            <phase>prepare-package</phase>
          </execution>
          <execution>
            <configuration>
              <rules>
                <rule>
                  <element>BUNDLE</element>
                  <limits>
                    <limit>
                      <counter>LINE</counter>
                      <minimum>0.80</minimum>
                      <value>COVEREDRATIO</value>
                    </limit>
                  </limits>
                </rule>
              </rules>
            </configuration>
            <goals>
              <goal>check</goal>
            </goals>
            <id>check</id>
          </execution>
        </executions>
        <groupId>org.jacoco</groupId>
        <version>0.8.15</version>
      </plugin>
      <plugin>
        <artifactId>sonar-maven-plugin</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>sonar</goal>
            </goals>
            <id>default-cli</id>
            <phase>verify</phase>
          </execution>
        </executions>
        <groupId>org.sonarsource.scanner.maven</groupId>
      </plugin>
      <plugin>
        <artifactId>pitest-maven</artifactId>
        <configuration>
          <mutationThreshold>70</mutationThreshold>
          <outputFormats>
            <outputFormat>XML</outputFormat>
            <outputFormat>HTML</outputFormat>
          </outputFormats>
          <withHistory>true</withHistory>
        </configuration>
        <dependencies>
          <dependency>
            <artifactId>pitest-junit5-plugin</artifactId>
            <groupId>org.pitest</groupId>
            <version>LATEST</version>
          </dependency>
        </dependencies>
        <executions>
          <execution>
            <goals>
              <goal>mutationCoverage</goal>
            </goals>
            <id>default-cli</id>
            <phase>verify</phase>
          </execution>
        </executions>
        <groupId>org.pitest</groupId>
        <version>1.19.1</version>
      </plugin>

    </plugins>
  </build>
  <dependencies>
    <dependency>
      <artifactId>spring-boot-h2console</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-actuator</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-cache</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-liquibase</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-webmvc</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <groupId>org.springdoc</groupId>
      <version>3.0.2</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-opentelemetry</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>micrometer-registry-prometheus</artifactId>
      <groupId>io.micrometer</groupId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-opentelemetry-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>h2</artifactId>
      <groupId>com.h2database</groupId>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <artifactId>lombok</artifactId>
      <groupId>org.projectlombok</groupId>
      <optional>true</optional>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-actuator-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-data-jpa-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-liquibase-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-webmvc-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-security</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>

    <dependency>
      <artifactId>spring-boot-starter-security-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>datasource-micrometer-spring-boot</artifactId>
      <groupId>net.ttddyy.observation</groupId>
      <version>2.2.1</version>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-security-oauth2-resource-server</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>

    <dependency>
      <artifactId>spring-boot-starter-security-oauth2-resource-server-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-security-oauth2-client</artifactId>
      <groupId>org.springframework.boot</groupId>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>spring-boot-starter-security-oauth2-client-test</artifactId>
      <groupId>org.springframework.boot</groupId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <artifactId>spring-ai-starter-model-google-genai</artifactId>
      <groupId>org.springframework.ai</groupId>
    </dependency>

  </dependencies>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <artifactId>spring-ai-bom</artifactId>
        <groupId>org.springframework.ai</groupId>
        <scope>import</scope>
        <type>pom</type>
        <version>2.0.0</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <description/>
  <developers>
    <developer/>
  </developers>
  <groupId>com.redmath</groupId>
  <licenses>
    <license/>
  </licenses>
  <modelVersion>4.0.0</modelVersion>
  <name/>
  <parent>
    <artifactId>spring-boot-starter-parent</artifactId>
    <groupId>org.springframework.boot</groupId>
    <relativePath/>
    <version>4.0.7</version> <!-- lookup parent from repository -->
  </parent>
  <properties>
    <java.version>25</java.version>
    <sonar.host.url>http://localhost:9000</sonar.host.url>
    <sonar.projectKey>Lecture02</sonar.projectKey>
    <sonar.projectName>Lecture02</sonar.projectName>
    <!--suppress UnresolvedMavenProperty -->
    <sonar.token>${env.SONAR_TOKEN}</sonar.token>
  </properties>
  <scm>
    <connection/>
    <developerConnection/>
    <tag/>
    <url/>
  </scm>

  <url/>

  <version>0.0.1-SNAPSHOT</version>

</project>
